version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-dapp
    working_dir: /var/www/html
    depends_on:
      - db
    volumes:
      - appdata:/var/www/html
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    depends_on:
      - app
    volumes:
      - appdata:/var/www/html
      - ./docker/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/production/certbot/www:/var/www/certbot
      - ./docker/production/certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/production/certbot/www:/var/www/certbot
      - ./docker/production/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"

volumes:
  dbdata:
  appdata:

